# Scan this file for changes every 30 seconds
refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S %Z)(utc)} {([{h({l})}]):>7} - {m}{n}"

  file:
    kind: rolling_file
    path: "logs/taskrs-server.log"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 50mb
      roller:
        kind: fixed_window
        base: 1
        count: 5
        pattern: "logs/taskrs-server.{}.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S %Z)(utc)} {([{l}]):>7} - {m}{n}"

root:
  level: trace
  appenders:
    - stdout
    - file