### GET Get all users (debug build only)
GET http://localhost:8080/api/v1/users
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2Mjc2NzYxNzIsImV4cCI6MTYzMDI2ODE3MiwidXNlciI6eyJpZCI6MSwiZW1haWwiOiJyb290QHRhc2tycy5jb20iLCJwYXNzd29yZCI6IiRhcmdvbjJpJHY9MTkkbT00MDk2LHQ9MyxwPTEkTmhGRFpFVnM1SG1NL0lSNjNubFBNUSRRR1ZYcmNLdVNDeTR0WGNjaW9DVWFDVVhtVTNOazdNczFPNnBFYWRsaU5zIiwiZmlyc3ROYW1lIjpudWxsLCJsYXN0TmFtZSI6bnVsbCwiYWN0aXZhdGVkIjp0cnVlLCJ1cGRhdGVkQXQiOiIyMDIxLTA3LTMwVDE0OjI5OjM0LjMxMDA3NiIsImNyZWF0ZWRBdCI6IjIwMjEtMDctMzBUMTQ6Mjk6MzQuMzEwMDc2In19.WR3O2lv_nFA5s57ewcpTa0FUYjiMi76ayIEX5GA41MM

### POST Create new user
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "id": 0,
  "email": "elon.musk2@mail.com",
  "password": "ToTheMoon",
  "firstName": "Elon",
  "lastName": "Musk"
}